version: 2.1

.distro-test: &distro-test
  docker:
    - image: cimg/python:3.7
  steps:
    - setup_remote_docker:
        version: 19.03.13
    - checkout
    - run: pip install -r test/requirements.txt
    - run: docker build -f test/_${DISTRO}.Dockerfile -t pytest_pihole:test_container ../
    - run: pytest -n auto test/test_automated_install.py

jobs:
  debian_9:
    <<: *distro-test
    environment:
      DISTRO: "debian_9"

workflows:
  version: 2.1
  build:
    jobs:
      - debian_9
